core/urls.py
from django.urls import path

from core import views


# Define o namespace para este conjunto de URLs
app_name = 'core'

# Lista de padrões de URL (rotas) mapeados para suas respectivas views
urlpatterns = [
    # Mapeia a URL raiz ('') para a view 'index' do módulo 
    # 'views' com o nome 'index'
    path('', views.index, name='index'),
]

estoque/urls.py
from django.urls import path, include

from estoque import views


app_name = 'estoque'


entrada_patterns = [
    # URL para a view que lista todas as entradas do estoque.
    path(
        '', 
        views.ListaEstoqueEntrada.as_view(), 
        name='lista_estoque_entrada'
    ),


    # URL para a view que adiciona uma nova entrada no estoque.
    path('adicionar/', views.add_estoque_entrada, name='add_estoque_entrada'),
]


saida_patterns = [
    # URL para a view que lista todas as saídas do estoque.
    path(
        '', 
        views.ListaEstoqueSaida.as_view(), 
        name='lista_estoque_saida'
    ),

    # URL para a view que adiciona uma nova saída no estoque.
    path('add/', views.add_estoque_saida, name='add_estoque_saida'),
]


urlpatterns = [
    # URL para a view que lista os detalhes das saidas no estoque.
    path(
        '<int:pk>/detalhes/', 
        views.DetalheEstoque.as_view(), 
        name='detalhes_estoque'
    ),
    path('entrada/', include(entrada_patterns)),
    path('saida/', include(saida_patterns)),
]

produto/urls.py
from django.urls import path

from produto import views


# Define o namespace para este conjunto de URLs
app_name = 'produto'

urlpatterns = [
    # URL para a view que lista todos os produtos
    path('', views.ProdutoList.as_view(), name='lista_produtos'),

    # URL para a view de detalhe de um produto específico
    path('<int:pk>/', views.detalhe_produto, name='detalhe_produto'),

    # URL para a view de formulário para adicionar um novo produto
    # com uma classe, utilizo o método as_view() para a chamada
    path('adicionar/', views.CriarProduto.as_view(), name='adicionar_produto'),

    # URL para editar um produto, com classe based views
    path(
        '<int:pk>/editar/', 
        views.EditarProduto.as_view(),
        name='editar_produto'
    ),
    
    # URL para retornar os detalhes do produto em formato JSON
    path('<int:pk>/json/', views.produto_json, name='produto_json'),

    path('import/csv/', views.import_csv, name='import_csv'),

    path('export/csv/', views.export_csv, name='export_csv'),

    path('import/excel/', views.importar_xlsx, name='importar_xlsx'),
    
    path('export/excel', views.export_xlsx, name='export_xlsx'),

    path(
        'import/csv/pandas',
        views.import_csv_with_pandas,
        name='import_csv_with_pandas'
    )

]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('produto/', include('produto.urls')),
    path('estoque/', include('estoque.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),   
]

core/models.py
from django.db import models

# Create your models here.

class TimeStampModel(models.Model):

    """
    Modelo abstrato que fornece campos de data/hora para 
    criação e última atualização.

    Attributes:
        criado_em (DateTimeField): Armazena a data e hora em 
        que a instância foi criada. 
        Preenchido automaticamente na criação.

        atualizado_em (DateTimeField): Armazena a data e hora da
        última atualização da instância. Atualizado automaticamente
        cada vez que a instância é salva.
    """

    criado_em = models.DateTimeField(
        'criado_em',
        auto_now_add=True,
        auto_now=False
    )

    atualizado_em = models.DateTimeField(
        'atualizado_em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        """
        Metadados para o modelo TimeStampModel.

        Attributes:
            abstract (bool): Se verdadeiro, indica que o modelo é 
            abstrato e não será criado no banco de dados. (Opcional)
        """
        abstract = True

core/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

core/templates/includes/nav.html
<!-- Criando minha navbar com bootstrap -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Estoque</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
    data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
    aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Home 
                <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01"
                data-toggle="dropdown" aria-haspopup="true" 
                aria-expanded="false">Produtos</a>

                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'produto:lista_produtos' %}">Lista de Produtos</a>
                    <a class="dropdown-item" href="{% url 'produto:import_csv' %}">Importar CSV</a>
                    <a class="dropdown-item" href="{% url 'produto:export_csv' %}">Exportar CSV</a>
                    <a class="dropdown-item" href="{% url 'produto:importar_xlsx' %}">Importar Excel</a>
                    <a class="dropdown-item" href="{% url 'produto:export_xlsx' %}">Exportar Excel</a>
                    <a class="dropdown-item" href="{% url 'produto:import_csv_with_pandas' %}">Importar com Pandas</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01"
                data-toggle="dropdown" aria-haspopup="true" 
                aria-expanded="false">Estoque</a>

                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'estoque:lista_estoque_entrada' %}">Entrada</a>
                    <a class="dropdown-item" href="{% url 'estoque:lista_estoque_saida' %}">Saída</a>
                </div>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <ul class="navbar-nav px-3">
                <li class="nav-item text-nowrap">
                    <a href="{% url 'logout' %}" class="nav-link">Sair</a>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>

core/templates/includes/pagination.html
<div class="row text-center">
    <div class="col-lg-12">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <!-- Link para a página anterior -->
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
        {% endif %}
  
        {% for pg in page_obj.paginator.page_range %}
          <!-- Sempre mostra as 3 primeiras e 3 últimas páginas -->
          {% if pg == 1 or pg == 2 or pg == 3 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' or pg == page_obj.paginator.num_pages|add:'-2' %}
  
            {% if page_obj.number == pg %}
              <!-- Página atual -->
              <li class="page-item active"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
            {% else %}
              <!-- Outras páginas que não são a atual -->
              <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
            {% endif %}
  
          {% else %}
  
            {% if page_obj.number == pg %}
              <!-- Página atual (quando não está entre as primeiras ou últimas 3) -->
              <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
            {% elif pg > page_obj.number|add:'-4' and pg < page_obj.number|add:'4' %}
              <!-- Mostra 3 páginas antes e 3 páginas depois da atual -->
              <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
            {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
              <!-- Ponto de elipse para indicar salto nas páginas -->
              <li class="page-item"><a class="page-link" href="">...</a></li>
            {% endif %}
  
          {% endif %}
        {% endfor %}
  
        {% if page_obj.has_next %}
          <!-- Link para a próxima página -->
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
        {% endif %}
      </ul>
    </div>
  </div>