core/urls.py
from django.urls import path

from core import views


# Define o namespace para este conjunto de URLs
app_name = 'core'

# Lista de padrões de URL (rotas) mapeados para suas respectivas views
urlpatterns = [
    # Mapeia a URL raiz ('') para a view 'index' do módulo 
    # 'views' com o nome 'index'
    path('', views.index, name='index'),
]

produto/urls.py
from django.urls import path

from produto import views


# Define o namespace para este conjunto de URLs
app_name = 'produto'

urlpatterns = [
    # URL para a view que lista todos os produtos
    path('', views.ProdutoList.as_view(), name='lista_produtos'),

    # URL para a view de detalhe de um produto específico
    path('<int:pk>/', views.detalhe_produto, name='detalhe_produto'),

    # URL para a view de formulário para adicionar um novo produto
    # com uma classe, utilizo o método as_view() para a chamada
    path('adicionar/', views.CriarProduto.as_view(), name='adicionar_produto'),

    # URL para editar um produto, com classe based views
    path(
        '<int:pk>/editar/', 
        views.EditarProduto.as_view(),
        name='editar_produto'
    ),
    
    # URL para retornar os detalhes do produto em formato JSON
    path('<int:pk>/json/', views.produto_json, name='produto_json'),

    path('import/csv/', views.import_csv, name='import_csv'),

    path('export/csv/', views.export_csv, name='export_csv'),

    path('import/excel/', views.importar_xlsx, name='importar_xlsx'),
    
    path('export/excel', views.export_xlsx, name='export_xlsx'),

    path(
        'import/csv/pandas',
        views.import_csv_with_pandas,
        name='import_csv_with_pandas'
    )

]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('produto/', include('produto.urls')),
    path('estoque/', include('estoque.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),   
]

produto/models.py
from django.db import models

from django.urls import reverse_lazy

# Create your models here.

class Produto(models.Model):

    """
    Representa um produto no sistema de estoque.

    Attributes:
        importado (bool): Indica se o produto é importado.
        ncm (str): Nomenclatura Comum do Mercosul, usado para 
        classificação fiscal.
        produto (str): Nome do produto, deve ser único.
        preco (Decimal): Preço do produto com até 5 dígitos antes do
        ponto decimal e 2 dígitos após o ponto decimal.
        estoque (int): Quantidade de unidades disponíveis em estoque.
        estoque_minimo (int): Quantidade mínima recomendada em estoque.
        categoria (ForeignKey): Referência à categoria do produto. Pode 
        ser nulo, se a categoria for removida, o campo é definido como 
        null.
    """
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preco', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque')
    estoque_minimo = models.PositiveIntegerField('estoque min', default=0)
    categoria = models.ForeignKey(
        'Categoria', 
        on_delete=models.SET_NULL, 
        null=True
    )

    class Meta:
        """
        Metadados para o modelo Produto.

        Attributes:
            ordering (tuple): Define a ordenação padrão das instâncias
            de Produto. No caso, os produtos serão ordenados pelo 
            campo 'produto' em ordem crescente.

        """
        ordering = ('produto',)

    def __str__(self):
        """
        Retorna a representação em string do produto.

        Returns:
            str: O nome do produto.
        """
        return f'{self.produto}'
    
    def get_absolute_url(self):
        """
        Retorna a URL absoluta para o detalhe de um produto específico.
        
        Returns:
            str: A URL para a visualização de detalhe do produto.
        """
        return reverse_lazy('produto:detalhe_produto', kwargs={'pk':self.pk})
    

    def dict_to_json(self):
        """
        Retorna um dicionário representando os dados do produto
        para conversão em JSON.

        Este método é utilizado para serializar os dados principais
        do produto em um formato de dicionário, adequado para 
        conversão em JSON, facilitando a integração com APIs ou 
        outras funcionalidades que requeiram dados em formato JSON.

        Returns:
            dict: Um dicionário contendo o identificador primário (pk), 
            o nome do produto, e a quantidade de estoque.
        """
        return {
            'pk': self.pk,
            'produto': self.produto,
            'estoque': self.estoque,
        }
    

class Categoria(models.Model):
    """
    Representa uma categoria de produtos.

    Attributes:
        categoria (str): O nome da categoria. Deve ser único e
        tem um tamanho máximo de 100 caracteres.

    Meta:
        ordering (tuple): Define a ordenação padrão para as instâncias
        do modelo pela categoria em ordem alfabética.
    """
    categoria = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ('categoria',)

    def __str__(self):
        """
        Retorna a representação em string da instância do modelo.

        Returns:
            str: O nome da categoria.
        """
        return self.categoria

produto/forms.py
from django import forms
from .models import Produto

class ProdutoForm(forms.ModelForm):
    """
    Formulário para criação e atualização de objetos do modelo Produto.

    Este formulário é baseado no modelo Produto e inclui 
    todos os campos do modelo.
    """

    class Meta:
        """
        Metadados para o formulário ProdutoForm.

        Atributos:
            model (Model): O modelo que será utilizado neste formulário.
            fields (str or list): Os campos do modelo a serem 
            incluídos no formulário.
        """
        
        # Define o modelo que será utilizado no formulário, 
        # que neste caso é o Produto
        model = Produto
        fields = '__all__' # Inclui todos os campos do modelo Produto

produto/views.py
import csv
from datetime import datetime
import io

from django.contrib import messages
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, ListView
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
import pandas as pd

from .models import Produto
from .forms import ProdutoForm
from produto.actions.import_xlsx import importar_xlsx as actions_importar_xlsx
from produto.actions.export_xlsx import exportar_xlsx as actions_exportar_xlsx

# Create your views here.

def lista_produtos(request):
    """
    View para listar todos os produtos.
    
    Args:
        request (HttpRequest): O objeto de solicitação HTTP.

    Returns:
        HttpResponse: A resposta HTTP com o template 
        `lista_produtos.html` renderizado.
    """
    nome_template = 'lista_produtos.html'

    # Recupera todos os objetos do modelo Produto
    objetos = Produto.objects.all()

    # Procura por um item no campo de busca
    search = request.GET.get('search')
    if search:
        objetos = objetos.filter(produto__icontains=search)
    
    # Define o contexto a ser passado para o template
    contexto = {'lista_objetos': objetos}

    # Renderiza o template com o contexto
    return render(request, template_name=nome_template, context=contexto)


class ProdutoList(ListView):
    """
    Classe-based view para listar produtos.
    
    Atributos:
        model (Model): O modelo que será utilizado na listagem.
        template_name (str): O nome do template que será renderizado.
        paginate_by (int): Quantidade de itens por página na paginação.
    """
    model = Produto
    template_name = 'lista_produtos.html'
    paginate_by = 10


def detalhe_produto(request, pk):
    """
    View para exibir os detalhes de um produto específico.
    
    Args:
        request (HttpRequest): O objeto de solicitação HTTP.
        pk (int): A chave primária do produto a ser exibido.

    Returns:
        HttpResponse: A resposta HTTP com o template 
        `detalhe_produto.html` renderizado.
    """
    nome_template = 'detalhe_produto.html'

    # Recupera o objeto Produto com a chave primária fornecida
    obj = Produto.objects.get(pk=pk)
    
    # Define o contexto a ser passado para o template
    contexto = {'objeto': obj}

    # Renderiza o template com o contexto
    return render(request, template_name=nome_template, context=contexto)


def adicionar_produto(request):
    nome_template = 'formulario_produto.html'
    return render(request, template_name=nome_template)


class CriarProduto(CreateView):
    """
    View baseada em classe para criar um novo produto.

    Atributos:
        model (Model): O modelo que será utilizado na view.
        template_name (str): O nome do template que será renderizado.
        form_class (Form): O formulário que será utilizado 
        para criar o objeto.
    """
    model = Produto
    template_name = 'formulario_produto.html'
    form_class = ProdutoForm


class EditarProduto(UpdateView):
    """
    View baseada em classe para editar um produto.

    Atributos:
        model (Model): O modelo que será utilizado na view.
        template_name (str): O nome do template que será renderizado.
        form_class (Form): O formulário que será utilizado 
        para criar o objeto.
    """
    model = Produto
    template_name = 'formulario_produto.html'
    form_class = ProdutoForm


def produto_json(request, pk):
    """
    Retorna os dados de um produto específico em formato JSON.

    Este método filtra o produto com base na chave primária 
    fornecida (pk), converte os dados principais do produto 
    em um formato de dicionário utilizando o método `dict_to_json`
    e retorna os dados como uma resposta JSON.

    Args:
        request (HttpRequest): O objeto de requisição HTTP.
        pk (int): A chave primária do produto a ser recuperado.

    Returns:
        JsonResponse: Um objeto de resposta JSON contendo os 
        dados do produto.
    """
    produto = Produto.objects.filter(pk=pk)
    data = [item.dict_to_json() for item in produto]
    return JsonResponse({'data': data})


def save_data(data):
    '''
    Salva os dados no banco.
    
    Args:
        data (list): Uma lista de OrderedDicts com os dados do CSV.
    '''
    aux = []
    for item in data:
        produto = item.get('produto')
        ncm = str(item.get('ncm'))
        importado = True if item.get('importado') == 'True' else False
        preco = item.get('preco')
        estoque = item.get('estoque')
        estoque_minimo = item.get('estoque_minimo')
        obj = Produto(
            produto=produto,
            ncm=ncm,
            importado=importado,
            preco=preco,
            estoque=estoque,
            estoque_minimo=estoque_minimo,
        )
        aux.append(obj)
    Produto.objects.bulk_create(aux)


def import_csv(request):
    """
    View para importar dados de um arquivo CSV e salvar no 
    banco de dados.

    Esta view processa o upload de um arquivo CSV contendo 
    dados de produtos, lê o conteúdo do arquivo, converte os dados em 
    um formato adequado e salva os dados no banco de dados.

    Args:
        request (HttpRequest): O objeto da requisição HTTP.

    Returns:
        HttpResponse: Se a requisição for POST e o arquivo for enviado,
        redireciona para a lista de produtos após salvar os dados.
        Se a requisição não for POST, renderiza o template de 
        upload de arquivo.
    """

    if request.method == 'POST' and request.FILES['myfle']:
        # Lê o arquivo enviado
        myfile = request.FILES['myfile']
        file = myfile.read().decode('utf-8')
        
        # Converte o conteúdo do arquivo em um DictReader
        reader = csv.DictReader(io.StringIO(file))
        
        # Cria uma lista de dicionários a partir do conteúdo do CSV
        data = [linha for linha in reader]
        
        # Salva os dados no banco de dados
        save_data(data)
        
        # Redireciona para a lista de produtos após salvar os dados
        return HttpResponseRedirect(reverse('produto:lista_produtos'))
    
    # Renderiza o template de upload de arquivo se a requisição não 
    # for POST
    template_name = 'import_produto.html'
    return render(request, template_name)


def export_csv(request):
    """
    Exporta dados de produtos para um arquivo CSV.

    Este método obtém todos os produtos do banco de dados e escreve
    suas informações em um arquivo CSV. Após a exportação, uma mensagem
    de sucesso é adicionada e o usuário é redirecionado para a lista de
    produtos.

    Args:
        request (HttpRequest): O objeto de solicitação HTTP.

    Returns:
        HttpResponseRedirect: Redireciona para a página de lista de 
        produtos após a exportação bem-sucedida.
    """

    header = (
        'importado', 'ncm', 'produto', 'preco', 'estoque', 'estoque_minimo',
    )

    # Obtém todos os produtos do banco de dados, selecionando 
    # apenas os campos definidos no cabeçalho
    produtos = Produto.objects.all().values_list(*header)
    with open('fix/produtos_exportados.csv', 'w') as csvfile:
        produto_writer = csv.writer(csvfile)
        produto_writer.writerow(header)
        for produto in produtos:
            produto_writer.writerow(produto)

    # Adiciona uma mensagem de sucesso para ser exibida ao usuários
    messages.success(request, 'Produtos exportados com sucesso.')
    return HttpResponseRedirect(reverse('produto:lista_produtos'))


def importar_xlsx(request):
    """
    View para importar produtos de um arquivo XLSX.

    Lê um arquivo XLSX contendo dados de produtos e salva esses 
    dados no banco de dados.

    Args:
        request (HttpRequest): A solicitação HTTP recebida pelo 
        servidor.

    Returns:
        HttpResponseRedirect: Redireciona o usuário para a lista 
        de produtos após a importação bem-sucedida.
    """
    filename = 'fix/produtos.xlsx'
    actions_importar_xlsx(filename)
    messages.success(request, 'Produtos importados com sucesso.')
    return HttpResponseRedirect(reverse('produto:lista_produtos'))


def export_xlsx(request):
    """
    View para exportar produtos para um arquivo XLSX.

    Gera um arquivo XLSX contendo dados de produtos e o envia 
    como resposta HTTP para download.

    Args:
        request (HttpRequest): A solicitação HTTP recebida pelo 
        servidor.

    Returns:
        HttpResponse: Resposta HTTP contendo o arquivo XLSX para 
        download.
    """
    data = datetime.now().strftime('%Y-%m-%d')
    model = 'Produto'
    filename = 'produtos_exportados.xlsx'
    _filename = filename.split('.')
    filename_final = f'{_filename[0]}_{data}.{_filename[1]}'

    # Obtem os dados dos produtos a serem exportados
    queryset = Produto.objects.all().values_list(
        'importado',
        'ncm',
        'produto',
        'preco',
        'estoque',
        'estoque_minimo',
        'categoria__categoria'
    )

    # Define as colunas do arquivo XLSX
    columns = (
        'Importado', 
        'NCM', 
        'Produto', 
        'Preço', 
        'Estoque', 
        'Estoque Minimo', 
        'Categoria'
    )

    # Gera a resposta HTTP com o arquivo XLSX
    response = actions_exportar_xlsx(model, filename_final, queryset, columns)
    return response


def import_csv_with_pandas(request):
    filename = 'fix/produtos.csv'
    df = pd.read_csv(filename)
    aux = []
    for row in df.values:
        obj = Produto(
            produto=row[0],
            ncm = row[1],
            importado = row[2],
            preco = row[3],
            estoque = row[4],
            estoque_minimo = row[5]
        )
        aux.append(obj)
    Produto.objects.bulk_create(aux)
    messages.success(request, 'Produtos importados com sucesso.')
    return HttpResponseRedirect(reverse('produto:lista_produtos'))

produto/templates/detalhe_produto.html
{% extends "base.html" %}

{% block conteudo %}

<a href="{% url 'produto:lista_produtos' %}">Voltar</a>

<h1>
{{ objeto }}
<span class="pull-right"><a href="{% url 'produto:editar_produto' objeto.pk %}">
    <button type="button" class="btn btn-success">
        <span class="fa fa-pecil"></span>Editar
    </button>
</a></span>
</h1>

<div class="col-sm-6">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-right">Importado</th>
                <td>
                    {% if objeto.importado %}
                        <i class="fa fa-check-circle ok"></i>
                    {% else %}
                        <i class="fa fa-minus-circle no"></i>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th class="text-right">NCM</th>
                <td>{{ objeto.ncm }}</td>
            </tr>
            <tr>
                <th class="text-right">Preço</th>
                <td>R$ {{ objeto.preco }}</td>
            </tr>
            <tr>
                <th class="text-right">Estoque</th>
                <td>{{ objeto.estoque }}</td>
            </tr>
            <tr>
                <th class="text-right">Estoque minímo</th>
                <td>{{ objeto.estoque_minimo }}</td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock conteudo %}

produto/templates/formulario_produto.html
{% extends "base.html" %}

{% load static %}

<!-- Carrega a biblioteca widget_tweaks para customizar widgets de formulários -->
{% load widget_tweaks %}

<!-- Início do bloco 'conteudo' que será inserido no 'base.html' -->
{% block conteudo %}

<form method="POST" novalidate>
    <!-- Início do formulário. O método POST é usado para enviar dados ao servidor -->
    <!-- Adiciona um token CSRF oculto ao formulário. O CSRF (Cross-Site Request Forgery) 
    é uma medida de segurança que protege contra ataques CSRF, garantindo que os 
    dados do formulário sejam enviados a partir da sua aplicação e 
    não de uma fonte externa maliciosa. -->
    {% csrf_token %}
    <!-- Token CSRF para proteger contra ataques CSRF -->
    {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.id_for_label }}">
                {% if field.field.required %}
                    <span class="required">{{ field.label }} </span>
                {% else %}
                    {{ field.label }}
                {% endif %}
            </label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
                <span class="text-muted">{{ error }}</span>
            {% endfor %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock conteudo %}
<!-- Fim do bloco 'conteudo' -->


{% block js %}
    <script src="{% static 'js/produto.js' %}"></script>
{% endblock js %}

produto/templates/import_produto.html
{% extends "base.html" %}

{% load static %}

<!-- Carrega a biblioteca widget_tweaks para customizar widgets de formulários -->
{% load widget_tweaks %}

<!-- Início do bloco 'conteudo' que será inserido no 'base.html' -->
{% block conteudo %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit" class="btn btn-success">Upload</button>
</form>

{% endblock conteudo %}
<!-- Fim do bloco 'conteudo' -->


{% block js %}
    <script src="{% static 'js/produto.js' %}"></script>
{% endblock js %}

produto/templates/lista_produtos.html
{% extends "base.html" %}

{% block conteudo %}
    <!-- Loop para exibir mensagens de feedback para o usuário -->
    {% for message in messages %}
        {% if 'success' in message.tags %}
            <!-- Mensagem de sucesso com formatação especial -->
            <p class="alert alert-success" role="alert"><span style="font-weight: bold;">{{ message }}</span></p>
        {% else %}
            <!-- Mensagem de erro ou alerta com formatação especial -->
            <p class="alert alert-danger" role="alert"><span style="font-weight: bold;">{{ message }}</span></p>
        {% endif %}
    {% endfor %}

    <div class="row">
        <div class="col-sm-6">
            <!-- Formulário de busca -->
            <form action="." method="GET" class="form-inline">
                <!-- Campo de texto para entrada de busca -->
                <input type="text" class="form-control" id="search" name="search" placeholder="Procurar por">
                <!-- Botão de submissão para o formulário de busca -->
                <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="Buscar">
            </form>
        </div>
    </div>

    <div class="page-header">
        <!-- Título da seção de produtos -->
        <h2>Lista de Produtos
            <span class="pull-right">
                <!-- Link para adicionar um novo produto -->
                <a href="{% url 'produto:adicionar_produto' %}">
                    <button type="button" class="btn btn-primary">
                        <span class="fa fa-plus"></span> Adicionar
                    </button>
                </a>
            </span>
        </h2>

        {% if object_list %}
            <!-- Tabela que exibe a lista de produtos -->
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center">Importado</th>
                        <th>NCM</th>
                        <th>Produto</th>
                        <th>Preço</th>
                        <th class="text-center">Estoque</th>
                        <th class="text-center">Estoque Mínimo</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Loop para exibir cada produto na tabela -->
                    {% for objeto in object_list %}
                        <tr>
                            <td class="text-center">
                                <!-- Exibe um ícone baseado no status de importação do produto -->
                                {% if objeto.importado %}
                                    <i class="fa fa-check-circle ok"></i>
                                {% else %}
                                    <i class="fa fa-minus-circle no"></i>
                                {% endif %}
                            </td>
                            <td>{{ objeto.ncm }}</td>
                            <td>
                                <!-- Link para a página de detalhes do produto -->
                                <a href="{{ objeto.get_absolute_url }}">{{ objeto.produto }}</a>
                            </td>
                            <td>R$ <span class="pull-right">{{ objeto.preco }}</span></td>
                            <td class="text-center">{{ objeto.estoque }}</td>
                            <td class="text-center">{{ objeto.estoque_minimo }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <!-- Mensagem exibida quando não há produtos na lista -->
            <p class="alert alert-warning">Sem itens na lista</p>
        {% endif %}
    </div>

    <!-- Inclui o template de paginação -->
    {% include "includes/pagination.html" %}
{% endblock conteudo %}

{% block js %}
    <script>
        // Script para remover mensagens de feedback após 2 segundos
        window.setTimeout(function(){
            $('.alert').fadeTo(500, 0).slideUp(500, function(){
                $(this).remove();
            });
        }, 2000);
    </script>
{% endblock js %}